version: '2'
services:
  postgres:
    image: postgres:9.6-alpine
    ports:
    - 5432:5432
    volumes:
    - ${HOME}/docker-volumes/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
